name: Learn CICD

on:
  #push:
  #  branches: [ "develop" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Install dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Send positive message in Slack
        if: ${{ success() }}
        run:         
          curl -X POST -H 'Content-type: application/json' --data '{"text":"The job in CICD Learn has succeeded"}' https://hooks.slack.com/services/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

      - name: Send negative message in Slack
        if: ${{ success() }}
        run:         
          curl -X POST -H 'Content-type: application/json' --data '{"text":"The job in CICD Learn has NOT succeeded!"}' https://hooks.slack.com/services/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
