name: Learn CICD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      #- name: Install dependencies
      #  run: npm ci

      #- name: Build assets
      #  run: npm run build

      #- name: Run tests
      #  run: npm run test
      
      # need add SLACK_WEBHOOK_URL in github.com => repository => setting => secrets
      - name: Send SLack message
        id: slack
        uses: slackapi/slack-github-action@v1.19.0
        with:
         payload: |
          {
            "text": "Наконец-то!!! GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
          }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
